Update usage. Fix git-mv commands

diff --git a/bin/git-cp-commit-work b/bin/git-cp-commit-work
--- a/bin/git-cp-commit-work
+++ b/bin/git-cp-commit-work
@@ -1,20 +1,31 @@
 #!/bin/bash -e
 
 ##
-# Copy files from commit to work (The commit is unaffected)
+# Description
+# -----------
+# Copy files from commit to work (The stage is unaffected)
+#
+# Error handling
+# --------------
+# For each file, ignore failure (if any) during copying and move on to the next.
 ##
-
-#!/bin/bash -e
 
 # -------------------------------------------------------------------------------------------------
 # Functions
 # -------------------------------------------------------------------------------------------------
 BASEDIR=$(dirname $(readlink -f ${0}))
+BASENAME=$(basename ${0})
+
 source "${BASEDIR}/util.sh"
 
 function usage {
-  echo "Copy files from commit to work (The commit is unaffected)"
-  echo "Usage: ${0} <file1> [<file2 ... <filen>]"
+echo "Copy files from commit (defaults to 'HEAD') to work
+
+Usage : ${BASENAME} [ <commit> -- ] <file1> [<file2 ... <filen>]
+
+Examples:
+  ${0} HEAD -- a.txt b.txt
+  ${0} a.txt b.txt c.txt"
   exit 0
 }
 
@@ -31,20 +42,19 @@ then
   dieUsage "Invalid argument count ${#}"
 fi
 
+commit=""
+if [[ "$2" == "--" ]]
+then
+  commit="${1}"
+  shift 2 
+fi
+
 # -------------------------------------------------------------------------------------------------
 # Main
 # -------------------------------------------------------------------------------------------------
-
-# A soft reset
-#   - Moves all the files currently pointed by HEAD to stage
-#   - Now, if the file exists in stage then no operation is done (it is NOT overwritten), else the file is staged.
-# Point the HEAD to previous commit (HEAD = HEAD - 1)
-# So, at this all the files that where committed (are now not commited) are just staged.
-git reset --soft HEAD~1
-git reset -- "${@}"
-
-# Move the files provided by user from stage to untrack (workspace)
-git-mv-stage-work "${@}"
-
-# Commit the rest of the files with the message of original head
-git commit -C ORIG_HEAD
+set +e
+for curr in "${@}"
+do
+  git-cat-commit-file ${commit} ${curr} > ${curr}
+done
+set -e
diff --git a/bin/git-mv-head-work b/bin/git-mv-head-work
--- a/bin/git-mv-head-work
+++ b/bin/git-mv-head-work
@@ -1,19 +1,22 @@
 #!/bin/bash -e
 
 ##
-# Move files from commit to work. The file be removed from commit and shall now be untracked.
-# This is an undo operation for  both 'git add <file>' 'git commit <file>'. So, it's as if, the files were never added to commit.
+# Move files from HEAD to work. The file be removed from HEAD and shall now be untracked.
+# This is an undo operation for both 'git add <file>' 'git commit <file>'. So, it's as if, the files were never added to HEAD.
 ##
 
 # -------------------------------------------------------------------------------------------------
 # Functions
 # -------------------------------------------------------------------------------------------------
 BASEDIR=$(dirname $(readlink -f ${0}))
+BASENAME=$(basename ${0})
+
 source "${BASEDIR}/util.sh"
 
 function usage {
-  echo "Move files from <commit> (defaults to HEAD) to workspace"
-  echo "Usage: ${0} [<commit>] <file1> [<file2 ... <fileN>]"
+  echo "Move files from HEAD to workspace"
+  echo ""
+  echo "Usage: ${BASENAME} <file1> [<file2 ... <fileN>]"
   exit 0
 }
 
@@ -34,14 +37,26 @@ fi
 # Main
 # -------------------------------------------------------------------------------------------------
 
+# Error out if there are any stage files.
+# This is required because as part of soft reset (in next step) commit files will be staged (if no staged file already exists)
+# If a staged file exists then it will not be overwritten. However, we want all commit files to be staged -- So stage MUST be empty
+list=$(git-ls-stage-files)
+if [[ ! -z "${list}" ]]
+then
+  echo "Error: Following files are staged. Please ensure there are no staged files for this command."
+  echo "---------------------------------------  Staged Files  ------------------------------------------"
+  echo "$(git-ls-stage-files)"
+  echo "-------------------------------------------------------------------------------------------------"
+  exit 1
+fi
+
 # Since it's 'soft', move all the files pointed by HEAD to index(stage)
 # Point the HEAD to previous commit (HEAD = HEAD - 1)
 # So, at this all the files that where committed (are now not commited) are just staged.
 git reset --soft HEAD~1
-git reset -- "${@}"
 
-# Move the files provided by user from stage to untrack (workspace)
-git-index-rm "${@}"
+# Move the files provided by user from stage to work
+git-mv-stage-work ${@}
 
 # Commit the rest of the files with the message of original head
 git commit -C ORIG_HEAD
